### ISSUE TITLE
att/owners team assigned as contributors?

### ISSUE THREAD

**Issue by cscheid** [att/pox#9]
Any reason for this? I keep getting a lot of emails about issues and pull requests, and I'd rather not :)

**Comment by changbl** [comment]
Hi Carlos,

I did not setup any email notifications on this project. I thought by
default Github only notifies people who watch the project or contribute
code to it.

I do notice you are on the watch list though. Maybe remove yourself from
the watch list?

Thanks

Changbin

**Comment by cscheid** [comment]
Hm. I didn't add myself to the watch list. Maybe someone added the att/owners team as collaborators?

Could it be that owners are added as collaborators to _every_ repository? That would be hugely inconvenient.

I'll unwatch this repo, and see what happens with other ones.
